Style/Documentation:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
Metrics/LineLength:
    Max: 120
Metrics/BlockLength:
    Exclude:
        - '**/*.gemspec'
        - '**/*_spec.rb'