FROM ruby:2.7
RUN apt-get update -qq && apt-get install -y postgresql-client curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt-get install nodejs
RUN mkdir /opencell
WORKDIR /opencell
COPY Gemfile /opencell/Gemfile
COPY Gemfile.lock /opencell/Gemfile.lock
COPY package.json /opencell/package.json
RUN bundle install --jobs 20 --retry 5 --without development test
RUN npm install
COPY . /opencell
ARG SECRET_KEY
RUN bundle exec rake RAILS_ENV=production SECRET_KEY_BASE=${SECRET_KEY} assets:precompile
# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000 2222

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0", "-e", "production"]