version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234 -- bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/opencell
    ports:
      - "1234:1234"
      - "3000:3000"
      - "26162:26162"
    depends_on:
      - db