require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe LabgroupsController, type: :controller do
  # Labgroup. As you add validations to Labgroup, be sure to
  # adjust the attributes here as well.

  before :each do
    @request.env["devise.mapping"] = Devise.mappings[:user]
    @user = create(:user, role: User.roles[:patient])
    @client = create(:client)
    Sample.with_user(@user) do
      @sample = create(:sample, client: @client)
    end
    session[:labgroup] = @client.labgroup.id
    session[:lab] = @client.labgroup.labs.first.id
    sign_in @user
  end

  let(:valid_attributes) do
    { name: 'first group' }
  end

  let(:invalid_attributes) do
    { name: nil }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Labgroup.create! valid_attributes
      get :index
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      labgroup = Labgroup.create! valid_attributes
      get :show, params: { id: labgroup.id }
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get :new
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      labgroup = Labgroup.create! valid_attributes
      get :edit, params: { id: labgroup.id }
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Labgroup" do
        expect do
          post :create, params: { labgroup: valid_attributes }
        end.to change(Labgroup, :count).by(1)
      end

      it "redirects to the created labgroup" do
        post :create, params: { labgroup: valid_attributes }
        expect(response).to redirect_to(labgroup_url(Labgroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Labgroup" do
        expect do
          post :create, params: { labgroup: invalid_attributes }
        end.to change(Labgroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post :create, params: { labgroup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { name: 'new name' }
      end

      it "updates the requested labgroup" do
        labgroup = Labgroup.create! valid_attributes
        patch :update, params: {id: labgroup.id, labgroup: new_attributes }
        labgroup.reload
        expect(labgroup.name).to eq 'new name'
      end

      it "redirects to the labgroup" do
        labgroup = Labgroup.create! valid_attributes
        patch :update, params: {id: labgroup.id, labgroup: new_attributes }
        labgroup.reload
        expect(response).to redirect_to(labgroup_url(labgroup))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        labgroup = Labgroup.create! valid_attributes
        patch :update, params: {id: labgroup.id, labgroup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested labgroup" do
      labgroup = Labgroup.create! valid_attributes
      expect do
        delete :destroy, params: { id: labgroup.id }
      end.to change(Labgroup, :count).by(-1)
    end

    it "redirects to the labgroups list" do
      labgroup = Labgroup.create! valid_attributes
      delete :destroy, params: { id: labgroup.id }
      expect(response).to redirect_to(labgroups_url)
    end
  end
end
