 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/labgroups", type: :request do
  # Labgroup. As you add validations to Labgroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Labgroup.create! valid_attributes
      get labgroups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      labgroup = Labgroup.create! valid_attributes
      get labgroup_url(labgroup)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_labgroup_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      labgroup = Labgroup.create! valid_attributes
      get edit_labgroup_url(labgroup)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Labgroup" do
        expect {
          post labgroups_url, params: { labgroup: valid_attributes }
        }.to change(Labgroup, :count).by(1)
      end

      it "redirects to the created labgroup" do
        post labgroups_url, params: { labgroup: valid_attributes }
        expect(response).to redirect_to(labgroup_url(Labgroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Labgroup" do
        expect {
          post labgroups_url, params: { labgroup: invalid_attributes }
        }.to change(Labgroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post labgroups_url, params: { labgroup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested labgroup" do
        labgroup = Labgroup.create! valid_attributes
        patch labgroup_url(labgroup), params: { labgroup: new_attributes }
        labgroup.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the labgroup" do
        labgroup = Labgroup.create! valid_attributes
        patch labgroup_url(labgroup), params: { labgroup: new_attributes }
        labgroup.reload
        expect(response).to redirect_to(labgroup_url(labgroup))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        labgroup = Labgroup.create! valid_attributes
        patch labgroup_url(labgroup), params: { labgroup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested labgroup" do
      labgroup = Labgroup.create! valid_attributes
      expect {
        delete labgroup_url(labgroup)
      }.to change(Labgroup, :count).by(-1)
    end

    it "redirects to the labgroups list" do
      labgroup = Labgroup.create! valid_attributes
      delete labgroup_url(labgroup)
      expect(response).to redirect_to(labgroups_url)
    end
  end
end
