 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/labs", type: :request do
  # Lab. As you add validations to Lab, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Lab.create! valid_attributes
      get labs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lab = Lab.create! valid_attributes
      get lab_url(lab)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lab_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      lab = Lab.create! valid_attributes
      get edit_lab_url(lab)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Lab" do
        expect {
          post labs_url, params: { lab: valid_attributes }
        }.to change(Lab, :count).by(1)
      end

      it "redirects to the created lab" do
        post labs_url, params: { lab: valid_attributes }
        expect(response).to redirect_to(lab_url(Lab.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Lab" do
        expect {
          post labs_url, params: { lab: invalid_attributes }
        }.to change(Lab, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post labs_url, params: { lab: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lab" do
        lab = Lab.create! valid_attributes
        patch lab_url(lab), params: { lab: new_attributes }
        lab.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lab" do
        lab = Lab.create! valid_attributes
        patch lab_url(lab), params: { lab: new_attributes }
        lab.reload
        expect(response).to redirect_to(lab_url(lab))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        lab = Lab.create! valid_attributes
        patch lab_url(lab), params: { lab: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lab" do
      lab = Lab.create! valid_attributes
      expect {
        delete lab_url(lab)
      }.to change(Lab, :count).by(-1)
    end

    it "redirects to the labs list" do
      lab = Lab.create! valid_attributes
      delete lab_url(lab)
      expect(response).to redirect_to(labs_url)
    end
  end
end
